# ====================================== Orgs API =========================================

### Get All Orgs
GET http://localhost:3000/organizations

### Get Org by ID
GET http://localhost:3000/organizations/cc5700d3-93f5-4103-b28e-42f965c354f0
### Create new org
POST http://localhost:3000/organizations
Content-Type: application/json

{
  "name": "Org name",
  "slug": "org-slug",
  "domain": "http://exampledomain.com"
}

### Update org by ID
PATCH http://localhost:3000/organizations/cc5700d3-93f5-4103-b28e-42f965c354f0
Content-Type: application/json

{
  "name": "Updated Org Name"
}

### Delete org by ID
DELETE http://localhost:3000/organizations/cc5700d3-93f5-4103-b28e-42f965c354f0

# ======================================= Users API ========================================

### Get All Users
GET http://localhost:3000/users

### Get User by ID
GET http://localhost:3000/users/ad0f9c4c-f6d3-422c-9951-d485d013f834

### Create new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@gmail.com",
  "password": "12345678",
  "birthDate": "1990-01-01",
  "orgId": "cc5700d3-93f5-4103-b28e-42f965c354f0"
}

### Update user by ID
PATCH http://localhost:3000/users/0b68f21c-910c-4d26-aee3-6677b54d3ff3
Content-Type: application

{
  "name": "Updated Name"
}

### Delete user by ID
DELETE http://localhost:3000/users/0b68f21c-910c-4d26-aee3-6677b54d3ff3

### Test Error Handling (Uncomment to test)
GET http://localhost:3000/test-error